version: "2"

services:
  ####################### Postgres Definition #######################
  postgres:
    restart: always
    container_name: dsrp_postgres
    build:
      context: migrations
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_USER=dsrp
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=dsrp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dsrp

  ####################### Flyway Migration Definition #######################
  flyway:
    container_name: dsrp_flyway
    build:
      context: migrations
      dockerfile: Dockerfile.flyway.dev
    environment:
      - FLYWAY_USER=dsrp
      - FLYWAY_HOME=/flyway
      - FLYWAY_PASSWORD=test
      - FLYWAY_DB_NAME=dsrp
      - FLYWAY_DB_HOST=postgres
      - FLYWAY_URL=jdbc:postgresql://postgres/dsrp
      - FLYWAY_OUT_OF_ORDER=true
      - FLYWAY_CONNECT_RETRIES=60
      - METABASE_USER_PASSWORD=metabase_pass
    depends_on:
      - postgres
    networks:
      - dsrp

  ####################### Backend Definition #######################
  backend:
    restart: always
    container_name: dsrp_backend
    build:
      context: services/dsrp-api
    env_file: services/dsrp-api/.env
    ports:
      - 5000:5000
    volumes:
      - ./services/dsrp-api/:/app/
    depends_on:
      - flyway
      - redis
    networks:
      - dsrp

  ####################### Redis Definition #######################
  redis:
    image: redis:3.2-alpine
    container_name: dsrp_cache
    restart: always
    command: redis-server --requirepass redis-password
    ports:
      - "6379:6379"
    networks:
      - dsrp

  ####################### Frontend Definition #######################
  frontend:
    restart: always
    container_name: dsrp_frontend
    build:
      context: services/dsrp-web
    command: ["npm", "run", "serve"]
    volumes:
      - ./services/dsrp-web/src/:/app/src/
    ports:
      - 3000:3000
    depends_on:
      - backend
    env_file: ./services/dsrp-web/.env
    networks:
      - dsrp

  ####################### TUSD Definition #######################
  tusd:
    container_name: tusd
    build:
      context: services/tusd
    ports:
      - 1080:1080
    env_file: ./services/tusd/.env

  ####################### DOCUMENT_GENERATION Definition #######################
  docgen-api:
    restart: always
    container_name: docgen_api
    image: bcgovimages/doc-gen-api:v2.1.3
    command: ["npm", "run", "start"]
    environment:
      - APP_PORT=3030
      - CACHE_DIR=/tmp/tmp-reports
      - NODE_ENV=development
    #volumes:
    #  - ./services/docgen-api/:/carbone-api/
    ports:
      - 3030:3030
    networks:
      - dsrp

####################### Networks Definition #######################
networks:
  dsrp:
    driver: "bridge"

####################### Volumes Definition #######################
volumes:
  postgres-data:
