kind: Template
apiVersion: v1
metadata:
  name: postgresql
  creationTimestamp: null
parameters:
  - name: NAME
    displayName: Name
    description: A name used for all objects
    required: true
  - name: TAG
    required: true
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        shared: "true"
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${TAG}
          annotations: null
          from:
            kind: ImageStreamTag
            name: postgresql-9.6-oracle-fdw:v1-stable
            namespace: bcgov
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Local
