// Static Content
export const STORE_TEST_INFO = "STORE_TEST_INFO";
export const STORE_BULK_STATIC_CONTENT = "STORE_BULK_STATIC_CONTENT";

// Redux
export const REQUEST = "REQUEST";
export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const CLEAR = "CLEAR";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const UPDATE_MODAL_TITLE = "UPDATE_MODAL_TITLE";

// Authentication
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const STORE_KEYCLOAK_DATA = "STORE_KEYCLOAK_DATA";
export const STORE_USER_ACCESS_DATA = "STORE_USER_ACCESS_DATA";
export const LOGOUT = "LOGOUT";

// OrgBook
export const STORE_ORGBOOK_SEARCH_RESULTS = "STORE_ORGBOOK_SEARCH_RESULTS";
export const STORE_ORGBOOK_CREDENTIAL = "STORE_ORGBOOK_CREDENTIAL";

// OGC
export const STORE_PERMIT_HOLDERS = "STORE_PERMIT_HOLDERS";
export const STORE_WELLS = "STORE_WELLS";
export const STORE_SELECTED_WELL = "STORE_SELECTED_WELL";
export const STORE_LIABILITIES = "STORE_LIABILITIES";

// applications
export const STORE_APPLICATIONS = "STORE_APPLICATIONS";
export const STORE_APPLICATION = "STORE_APPLICATION";
