export const APPLICATION_FORM = "APPLICATION_FORM";
export const VIEW_APPLICATION_STATUS_FORM = "VIEW_APPLICATION_STATUS_FORM";
export const DOCUMENT_UPLOAD_FORM = "DOCUMENT_UPLOAD_FORM";
export const JUMP_TO_APPLICATION_FORM = "JUMP_TO_APPLICATION_FORM";
export const ADMIN_EDIT_APPLICATION_FORM = "ADMIN_EDIT_APPLICATION_FORM";
export const CONTRACTED_WORK_INTERIM_PAYMENT_FORM = "CONTRACTED_WORK_INTERIM_PAYMENT_FORM";
export const CONTRACTED_WORK_FINAL_PAYMENT_FORM = "CONTRACTED_WORK_FINAL_PAYMENT_FORM";
export const CONTRACTED_WORK_INTERIM_PROGRESS_REPORT_FORM =
  "CONTRACTED_WORK_INTERIM_PROGRESS_REPORT_FORM";
