export const APPLICATION_FORM = "APPLICATION_FORM";
export const VIEW_APPLICATION_STATUS_FORM = "VIEW_APPLICATION_STATUS_FORM";
export const INTERIM_CONTRACTED_WORK_PAYMENT_FORM = "INTERIM_CONTRACTED_WORK_PAYMENT_FORM";
export const FINAL_CONTRACTED_WORK_PAYMENT_FORM = "FINAL_CONTRACTED_WORK_PAYMENT_FORM";
export const INTERIM_PROGRESS_REPORT_CONTRACTED_WORK_PAYMENT_FORM =
  "INTERIM_PROGRESS_REPORT_CONTRACTED_WORK_PAYMENT_FORM";
export const DOCUMENT_UPLOAD_FORM = "DOCUMENT_UPLOAD_FORM";
export const JUMP_TO_APPLICATION_FORM = "JUMP_TO_APPLICATION_FORM";
export const ADMIN_EDIT_APPLICATION_FORM = "ADMIN_EDIT_APPLICATION_FORM";
