export const PAYMENT_TYPES = {
  INTERIM: "interim",
  FINAL: "final",
};

export const CONTRACTED_WORK_PAYMENT_STATUS = {
  INFORMATION_REQUIRED: "INFORMATION_REQUIRED",
  APPROVED: "APPROVED",
  READY_FOR_REVIEW: "READY_FOR_REVIEW",
};
