// Authentication
export const AUTHENTICATION = "AUTHENTICATION";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const UNAUTHENTICATE_USER = "UNAUTHENTICATE_USER";
export const GET_USER_INFO = "GET_USER_INFO";

// Misc
export const STATIC_CONTENT = "STATIC_CONTENT";
export const LOAD_ALL_STATIC_CONTENT = "LOAD_ALL_STATIC_CONTENT";
export const MODAL = "MODAL";
export const NETWORK = "NETWORK";

// OrgBook
export const ORGBOOK = "ORGBOOK";
export const ORGBOOK_SEARCH = "ORGBOOK_SEARCH";
export const ORGBOOK_CREDENTIAL = "ORGBOOK_CREDENTIAL";

// Application
export const APPLICATIONS = "APPLICATIONS";
export const CREATE_APPLICATION = "CREATE_APPLICATION";
export const CREATE_APPLICATION_STATUS = "CREATE_APPLICATION_STATUS";
export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const GET_APPLICATION = "GET_APPLICATION";
export const UPDATE_APPLICATION = "UPDATE_APPLICATION";
export const UPDATE_APPLICATION_REVIEW = "UPDATE_APPLICATION_REVIEW";

// OGC
export const OGC = "OGC";
export const FETCH_PERMIT_HOLDERS = "FETCH_PERMIT_HOLDERS";
export const FETCH_WELLS = "FETCH_WELLS";
export const FETCH_SELECTED_WELL = "FETCH_SELECTED_WELL";
export const FETCH_LIABILITIES = "FETCH_LIABILITIES";

// App Settings
export const GET_APP_SETTINGS = "GET_APP_SETTINGS";
export const APP_SETTINGS = "APP_SETTINGS";
export const UPDATE_APP_SETTING = "UPDATE_APP_SETTING";
