// Authentication
export const AUTHENTICATION = "AUTHENTICATION";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const UNAUTHENTICATE_USER = "UNAUTHENTICATE_USER";
export const GET_USER_INFO = "GET_USER_INFO";

// OTP AUTHORIZATION
export const GET_OTL = "GET_OTL";
export const GET_OTP = "GET_OTP";
export const END_USER_TEMPORARY_SESSION = "END_USER_TEMPORARY_SESSION";
export const AUTHORIZATION = "AUTHORIZATION";

// Misc
export const STATIC_CONTENT = "STATIC_CONTENT";
export const LOAD_ALL_STATIC_CONTENT = "LOAD_ALL_STATIC_CONTENT";
export const MODAL = "MODAL";
export const NETWORK = "NETWORK";

// OrgBook
export const ORGBOOK = "ORGBOOK";
export const ORGBOOK_SEARCH = "ORGBOOK_SEARCH";
export const ORGBOOK_CREDENTIAL = "ORGBOOK_CREDENTIAL";

// Application
export const APPLICATIONS = "APPLICATIONS";
export const CREATE_APPLICATION = "CREATE_APPLICATION";
export const CREATE_APPLICATION_STATUS = "CREATE_APPLICATION_STATUS";
export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const GET_APPLICATION = "GET_APPLICATION";
export const GET_APPLICATION_SUMMARY = "GET_APPLICATION_SUMMARY";
export const UPDATE_APPLICATION = "UPDATE_APPLICATION";
export const UPDATE_APPLICATION_REVIEW = "UPDATE_APPLICATION_REVIEW";
export const CREATE_APPLICATION_PAYMENT_DOCUMENT = "CREATE_APPLICATION_PAYMENT_DOCUMENT";
export const DELETE_APPLICATION_PAYMENT_DOCUMENT = "DELETE_APPLICATION_PAYMENT_DOCUMENT";
export const GET_APPLICATION_APPROVED_CONTRACTED_WORK = "GET_APPLICATION_APPROVED_CONTRACTED_WORK";
export const GET_APPLICATIONS_APPROVED_CONTRACTED_WORK =
  "GET_APPLICATIONS_APPROVED_CONTRACTED_WORK";
export const UPDATE_CONTRACTED_WORK_PAYMENT_INTERIM = "UPDATE_CONTRACTED_WORK_PAYMENT_INTERIM";
export const UPDATE_CONTRACTED_WORK_PAYMENT_FINAL = "UPDATE_CONTRACTED_WORK_PAYMENT_FINAL";
export const UPDATE_CONTRACTED_WORK_PAYMENT_INTERIM_REPORT =
  "UPDATE_CONTRACTED_WORK_PAYMENT_INTERIM_REPORT";
export const UPDATE_CONTRACTED_WORK_PAYMENT_AUDIT_STATUS =
  "UPDATE_CONTRACTED_WORK_PAYMENT_AUDIT_STATUS";
export const CREATE_CONTRACTED_WORK_PAYMENT_STATUS = "CREATE_CONTRACTED_WORK_PAYMENT_STATUS";
export const UPDATE_APPLICATION_ESTIMATED_COST_OVERRIDE =
  "UPDATE_APPLICATION_ESTIMATED_COST_OVERRIDE";

// DOCUMENTS
export const UPLOAD_DOCUMENTS = "UPLOAD_DOCUMENTS";

// OGC
export const OGC = "OGC";
export const FETCH_PERMIT_HOLDERS = "FETCH_PERMIT_HOLDERS";
export const FETCH_WELLS = "FETCH_WELLS";
export const FETCH_SELECTED_WELL = "FETCH_SELECTED_WELL";
export const FETCH_LIABILITIES = "FETCH_LIABILITIES";
export const FETCH_NOMINATED_WELLS = "FETCH_NOMINATED_WELLS";
export const FETCH_NOMINATED_SELECTED_WELL = "FETCH_NOMINATED_SELECTED_WELL";

// App Settings
export const GET_APP_SETTINGS = "GET_APP_SETTINGS";
export const APP_SETTINGS = "APP_SETTINGS";
export const UPDATE_APP_SETTING = "UPDATE_APP_SETTING";

// Company Pament Info
export const COMPANY_PAYMENT_INFO = "COMPANY_PAYMENT_INFO";
export const FETCH_COMPANY_PAYMENT_INFOS = "FETCH_COMPANY_PAYMENT_INFOS";
export const CREATE_COMPANY_PAYMENT_INFO = "CREATE_COMPANY_PAYMENT_INFO";
export const UPDATE_COMPANY_PAYMENT_INFO = "UPDATE_COMPANY_PAYMENT_INFO";
