apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nginx-bc-template
parameters:
  - description: stores image tag
    name: TAG
  - description: stores pr number
    name: PR
  - description: stores namespace
    name: NAMESPACE
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: dormant-site-reclamation-program-build-${TAG}
        app-name: dormant-site-reclamation-program
        build-config.name: dsrp-nginx-${TAG}
        change-id: "${PR}"
        env-id: ${TAG}
        env-name: build
        github-owner: bcgov
        github-repo: dormant-site-reclamation-program
        hash: d51204c538d66e760c9205f135f649870124ad70
      name: dsrp-nginx-${TAG}
      namespace: ${NAMESPACE}
    spec:
      completionDeadlineSeconds: 600
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: dsrp-nginx:${TAG}
          namespace: 269007-tools
      postCommit: {}
      resources: {}
      runPolicy: SerialLatestOnly
      source:
        contextDir: services/nginx
        git:
          ref: refs/pull/${PR}/head
          uri: https://github.com/bcgov/dormant-site-reclamation-program.git
        sourceSecret:
          name: github-credentials
        type: Git
      strategy:
        sourceStrategy:
          env:
            - name: NGINX_AUX_DIR
              value: auxiliary
            - name: OPENSHIFT_BUILD_CONFIG_HASH
              value: d51204c538d66e760c9205f135f649870124ad70
            - name: OPENSHIFT_BUILD_TREE_HASH
              value: 5e1673d431bf8d688857d4fc6905397cc5dfb773
            - name: _BUILD_HASH
              value: sha256:49bfb4881d69f300455d4de24d047399266f77467f238f839fe4faea24a451a4
          from:
            kind: ImageStreamTag
            name: bcgov-s2i-nginx:latest
            namespace: 269007-tools
        type: Source
      successfulBuildsHistoryLimit: 5
