import authenticationReducerObject from "./reducers/authenticationReducer";
import networkReducerObject from "./reducers/networkReducer";
import modalReducerObject from "./reducers/modalReducer";
import staticContentReducerObject from "./reducers/staticContentReducer";
import orgbookReducerObject from "./reducers/orgbookReducer";
import OGCReducerObject from "./reducers/OGCReducer";
import CompanyPaymentInfoReducerObject from "./reducers/CompanyPaymentInfoReducer";
import applicationReducerObject from "./reducers/applicationReducer";
import appSettingsReducerObject from "./reducers/appSettingsReducer";
import authorizationReducerObject from "./reducers/authorizationReducer";

export const authenticationReducer = authenticationReducerObject;
export const networkReducer = networkReducerObject;
export const modalReducer = modalReducerObject;
export const staticContentReducer = staticContentReducerObject;
export const orgbookReducer = orgbookReducerObject;
export const OGCReducer = OGCReducerObject;
export const CompanyPaymentInfoReducer = CompanyPaymentInfoReducerObject;
export const applicationReducer = applicationReducerObject;
export const appSettingsReducer = appSettingsReducerObject;
export const authorizationReducer = authorizationReducerObject;
