UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   CYPRESS A- 028-F/094-B-15' WHERE wa_number = 737;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   CYPRESS A- 086-C/094-B-15' WHERE wa_number = 827;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   CYPRESS D- 087-C/094-B-15' WHERE wa_number = 1326;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   CYPRESS A- 065-C/094-B-15' WHERE wa_number = 1339;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   CYPRESS A- 092-K/094-B-10' WHERE wa_number = 2365;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   CYPRESS D- 091-E/094-B-15' WHERE wa_number = 3420;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   CYPRESS B- 024-L/094-B-15' WHERE wa_number = 5693;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  N CYPRESS D- 077-L/094-B-15' WHERE wa_number = 5851;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   CYPRESS B- 027-K/094-B-15' WHERE wa_number = 8202;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   CYPRESS A- 017-F/094-B-15' WHERE wa_number = 12170;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS B- 007-F/094-B-15' WHERE wa_number = 15071;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS D- 067-F/094-B-15' WHERE wa_number = 15116;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS A- 070-F/094-B-15' WHERE wa_number = 15168;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CHOWADE D- 038-E/094-B-09' WHERE wa_number = 15294;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS B-A027-K/094-B-15' WHERE wa_number = 15449;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS B- 079-F/094-B-15' WHERE wa_number = 16227;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS A- 082-F/094-B-15' WHERE wa_number = 16374;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS B- 027-G/094-B-15' WHERE wa_number = 16406;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS D-A091-E/094-B-15' WHERE wa_number = 16623;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS C- 018-F/094-B-15' WHERE wa_number = 17245;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   GRAHAM C- 095-D/094-B-09' WHERE wa_number = 17569;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS B- 087-F/094-B-15' WHERE wa_number = 17949;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  CYPRESS C- 080-F/094-B-15' WHERE wa_number = 18033;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL ET AL  S JULIENNE B- 090-L/094-B-16' WHERE wa_number = 19931;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   DAIBER B- 098-D/094-B-16' WHERE wa_number = 21203;
UPDATE nominated_well_site SET operator = 'Canadian Natural Resources Limited', ba_id = 237, well_name = 'CNRL   JULIENNE A- 001-I/094-B-15' WHERE wa_number = 21805;