name: Deploy to dev

on:
  push:
    branches:
      - develop
    paths:
      - openshift4/templates/**.dc.yaml

env:
  TAG: dev
  SOURCE_REPOSITORY_URL: https://github.com/bcgov/dormant-site-reclamation-program.git
  SOURCE_REPOSITORY_REF: refs/pull/42/head
  APP_DOMAIN: dsrp-nginx-269007-dev.apps.silver.devops.gov.bc.ca

jobs:
  update-deployments:
    name: update-deployments
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          # - config: nodejs
          # - config: python36
          - name: dsrp-dbbackup
            config: dbbackup
          - name: dsrp-docgen
            config: docgen
          - name: dsrp-postgresql
            config: postgresql
          - name: dsrp-nginx
            config: nginx
          - name: dsrp-redis
            config: redis
          - name: dsrp-tusd
            config: tusd
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          version: "4.6"
      - name: oc login
        run: |
          oc login --token=${{ secrets.BUILD_TOKEN }} --server=${{ secrets.CLUSTER_API }}
      - name: Update infrastructure in dev
        run: |
          oc -n ${{secrets.NS_DEV}} process -f openshift4/templates/${{ matrix.config }}.dc.yaml --ignore-unknown-parameters=true \
          -p NAME=${{matrix.name}} \
          -p TAG=${{env.TAG}} \
          -p JWT_OIDC_WELL_KNOWN_CONFIG=https://test.oidc.gov.bc.ca/auth/realms/hud2v882/.well-known/openid-configuration \
          -p JWT_OIDC_AUDIENCE=dormant-application-dev \
          -p URL=https://dsrp-nginx-269007-dev.apps.silver.devops.gov.bc.ca \
          -p ENVIRONMENT_NAME=dev \
          -p DSRP_DOMAIN=${{env.APP_DOMAIN}} \
          | oc -n ${{secrets.NS_DEV}} apply -f -
