name: Promote to prod

on:
  workflow_dispatch:

env:
  ORIG_TAG: test
  PROMOTE_TAG: prod
  SOURCE_REPOSITORY_URL: https://github.com/bcgov/dormant-site-reclamation-program.git
  SOURCE_REPOSITORY_REF: refs/pull/42/head

jobs:
  initiate:
    name: initiate
    runs-on: ubuntu-20.04
    environment:
      name: production
    steps:
      - name: Waiting for approval
        run: |
          echo "Starting prod promotion..."

  promote-to-prod:
    needs: initiate
    name: promote-to-prod
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: dsrp-nginx
          - name: dsrp-postgres
          - name: dsrp-frontend
          - name: dsrp-python-backend
          - name: dsrp-flyway-migration-client
          # - name: dsrp-tusd
          # - name: dsrp-docgen
          # - name: dsrp-dbbackup

    steps:
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          version: "4.6"
      - name: oc login
        run: |
          oc login --token=${{ secrets.BUILD_TOKEN }} --server=${{ secrets.CLUSTER_API }}
      - name: Promote test to prod
        run: |
          oc -n ${{secrets.NS_TOOLS}} tag \
          ${{ secrets.NS_TOOLS }}/${{ matrix.name }}:${{ env.ORIG_TAG }} \
          ${{ secrets.NS_TOOLS }}/${{ matrix.name }}:${{ env.PROMOTE_TAG }}
      # - name: Rollout to prod
      #   run: |
      #     oc -n ${{ secrets.NS_PROD }} rollout latest ${{ matrix.name }}
